# Generated by Django 4.1.6 on 2023-02-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.carrinho'),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.games'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='item',
            field=models.ManyToManyField(through='plataforma.ItemCarrinho', to='plataforma.games'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
